### ISSUE TITLE
On-Screen Lighting-Up Piano Keyboard

### ISSUE THREAD

**Issue by barak** [pianobooster/PianoBooster#200]
(This feature request comes from my eight-year-old daughter. I will relay any requests for clarification to her.)

She says the game would be more fun if there were a toggle option to display a piano keyboard at the bottom of the screen, on which the correct key to press next would light up. Perhaps the time until it should be pressed could be shown, by changing color or by gradually filling it up or some such.

**Comment by glixx** [comment]
We have piano keyboard widget.

**Comment by glixx** [comment]
https://github.com/captnfab/PianoBooster/issues/38

**Comment by hpladds** [comment]
There is a feature that improved the game-like experience for my kids by
color-coding the notes displayed in the songs' scores.

This feature allowed my kids to see a blue-colored C note displayed in the
score. They would then look for and press a blue-colored C key on the
keyboard. (I would place colored stickers on the keys). If a red D note was
displayed, they would look for the red-stickered key and press it. If a
green A note, they would press the green-stickered key, and so on... each
key/note combination in having its own color.

It has been suggested that this feature be pulled into version 0.7.0, but I
believe that it would be wiser to have the feature toggled on and off
before including it in the code.  In this way, as the child becomes better
at correlating the score notes to the associated keys, then they can be
weened off the color-coding.

I have yet to try the code in 0.7.0, but the draw.cpp file (which
introduces this feature) may be found here:
 https://github.com/hpladds/PiPianoBooster  -- please note the link in the
"History of Pianobooster" portion, it can take you directly to the draw.cpp
file. Otherwise a full download is available; it has worked on a Rasp Pi 3
B and various Ubuntu desktop environments for me.

**Comment by barak** [comment]
I just filed a pull request https://github.com/captnfab/PianoBooster/pull/202 which has the KORY colour-coded-notes code, wrapped by some config toggle logic.
