### ISSUE TITLE
Played notes not recognized

### ISSUE THREAD

**Issue by Faldrian** [pianobooster/PianoBooster#207]
Setup:
- JACK + Midi-Keyboard
- PianoBooster - Version 0.7.1 (arch-linux: pianobooster-qt5-git-r1078.654ea25-1)
- Calf with Fluidsynth

What works:
- pianobooster can load midi-files, play them in "listen"-mode and it sounds great and works so far

what does not work:
when I play notes on my midi-keyboard, they are only recognized when I play at least 2 notes at the same time. In that case only one of the 2 is passed on to fluidsynth.

When I play a single note, it is not recognized.

When I wire my midi keyboard directly to fluidsynth, every note is recognized and played, as it should be.

The real wiring should be (inside JACK): midi-in -> rtmidi -> fluidsynth
(as pianobooster will pass the notes, I assumed?)

Any idea what is wrong, so pianobooster does not recognize my played notes?

**Comment by louis-barman** [comment]
OK this is now fixed please check the the develop branch of my fork of the pianobooster project  (see https://github.com/louis-barman/PianoBooster) Please can you confirm this is fixed so that this issue can be closed.

{Also I could not get Jack working at all (Jack seems overly complicated and not suitable for beginners) so I restored the original use of Linux ALSA which how the original piano booster use to work -- and incase you are wondering I am the original author of piano booster. }

**Comment by pianobooster** [comment]
Fixed. Please see the code in the develop branch. Thank for raising this.
