### ISSUE TITLE
Is it only for midi keyboard? 

### ISSUE THREAD

**Issue by zzm88** [pianobooster/PianoBooster#251]
Is there any way I can use it to practice a real piano( through microphone)?

**Comment by pkillnine** [comment]
What you need is a realtime audio-to-MIDI converter. I found this thread which mentions some FOSS options: https://linuxmusicians.com/viewtopic.php?t=17240

**Comment by louis-barman** [comment]
I **really** recommend getting a midi keyboard. You do not need to use any of the keyboard sounds as piano booster has a built-in fluid synth sound generator.  Even a midi keyboard with smaller keys works fine and you can then easily transfer your skills back to the real piano.

There are two potential problems with using a microphone as suggested above. 

1. You would always need to wear headphones to hear the PianoBooster sound output otherwise the microphone would pick up everything including PianoBooster output.
2. There will **always** be a delay before the realtime audio-to-MIDI converter detects what you are playing and this will delay the piano booster output making it play out of time.  An audio-to-MIDI converter needs to first hear the note you are playing before it can output the midi note that you are playing. Also audio-to-MIDI converters probably don't work well detecting chords played on the piano. (disclaimer i haven't actually tired this out)

Midi keyboards are not too expensive especially second hand midi keyboards.

**Comment by louis-barman** [comment]
see: https://www.pianobooster.org/faq.html#will-piano-booster-work-with-a-real-piano
