### ISSUE TITLE
How to use fluidsynth on MacOS?

### ISSUE THREAD

**Issue by LaiZhou** [pianobooster/PianoBooster#257]
**Case 1**
`
EXPERIMENTAL_USE_FLUIDSYNTH="ON"
`

I installed the fluidsynth through homebrew.
But when I build the project, it failed.

`
fluidsynth development package not found
`

**Case 2**
`
EXPERIMENTAL_USE_FLUIDSYNTH="OFF"
`
The build process is ok.But when I use the PianoBooster , no output midi devicies to select.

**Comment by louis-barman** [comment]
Hi just checking you have seen the pre-built mac executable of PREVIEW of PianoBooster-0.7.3 that is available on the official website  http://pianobooster.sourceforge.net/ . So no need to compile from source. Please can you test that this prebuilt mac executable version works for you and can you please post your reply on this thread http://piano-booster.2625608.n2.nabble.com/Preview-of-NEW-PianoBooster-executable-for-Windows-amp-Linux-td7572821.html. 

I presume you closed this issue because you got this working OK. But if you really want to compile from source you are better off using the develop branch rather than the master branch. And please don't forget to post to confirm whether the mac executable works for you. Thanks.

**Comment by LaiZhou** [comment]
@louis-barman ,year,I got it work.
I use the master branch to build the source.
What I changed in the .pro was:
`
DEFINES +=__MACOSX_CORE__
LIBS += -framework CoreMidi -framework CoreAudio -framework CoreServices
`
it works for me.

But when I try to build it on IOS Platform, it comes with the error：
`
~/PianoBooster-master/src/Draw.h:32: error: 'OpenGL/gl.h' file not found
  #include <OpenGL/gl.h>
           ^~~~~~~~~~~~~
`
I wonder if I can build the source on  IOS Platform now with a bit of modifications .
I want migrate  PianoBooster to IPad, Do you have any roadmap about it?

**Comment by louis-barman** [comment]
Sorry there are no plans to migrate the iPad or iOS. I don't have an iPhone and iPad and cannot even compile for iOS. I suspect you will hit the same problems as others who tried to compile it on Android. PB uses the full features of the opengl that are not available in opengl es.

**Comment by LaiZhou** [comment]
@louis-barman thank you.
