### ISSUE TITLE
Better handling of the music books (BoosterMusicBooks.zip)

### ISSUE THREAD

**Issue by fred-wang** [pianobooster/PianoBooster#265]
As I see, the current situation is:

1. One has to call make in music/src/ to generate all the content in doc/courses/ (i.e. midi & svg files + README.html and README.md)

2. One has to execute tools/make_music.sh to generate the zip file (containing a copy of the midi files and new html doc per music piece)

3. All these files are actually tracked in the repo, not generated by the CMake build system.

4. The zip file is extracted at run time (if the MUSIC_RELEASE version changed) in `CSettings::unzipBoosterMusicBooks()` ; or at install time on windows.

This seems a bit complicate and make difficult to contribute new music pieces.

Proposals:

Step 1: Instead of unzipping the zip file at runtime, just add a preference for the path to the (unzipped) BoosterMusicBooks directory.

Step 2: Integrate the generation of all of this in the cmake system and remove the generated files from the repo.

Unless I'm missing something, I don't think "Step 1" would be problematic. "Step 2" is probably more difficult as the scripts might be very platform-specific. So maybe an easier alternative would be:

Step 2 bis: Create a separate repository  captnfab / PianoBoosterMusicBooks github repository where one would move the music source and unix scripts to generate their output, as well as released zip archives. Then the builder / installer would just download the release from there, instead of storing content in the PianoBooster repo.

WDYT?

**Comment by fred-wang** [comment]
(I forgot to say, but also localization of the music books does not seem really easy right now with the current setup)

**Comment by louis-barman** [comment]
The script `tools/make_music.sh` has now been deleted in the **develop** branch and replaced with `music/src/makemusic.py`. 

{ @captnfab  Please could you make the default branch of this repo the **develop** branch as I don't have access rights to this repo to make this change myself. @captnfab I have just resent you the  email requesting this change as I suspect previous emails requesting this may have gone into your spam folder. Thanks }

The localisation of the music books of the music books has never worked with the previous setup but they now work very nicely using on the develop branch `music/src/makemusic.py`. The `makemusic.py` will also allow me to update the PB website with all the music.


However there is normally no need to run this script unless you are contributing new music or making fresh translations to music book since the everything is already built within the `BoosterMusicBooks.zip` release zip file.

I am planning to move the  source for the PianoBoosterMusicBooks  into there own github repo  and so agree with your _"Step 2 bis:"_ suggestion.

@fred-wang you wrote  _"... to contribute new music pieces"._ Do you some new music pieces that you would like to contribute??

**Comment by fred-wang** [comment]
@louis-barman Thanks, makemusic.py seems to work great indeed. Looking forward to seeing a separate repo. The name of the book / song does not seem localized though. I'm considering relying on PianoBooster to teach elementary keyboard playing to children at a local association. So I'm indeed thinking about adding simple exercise in BeginnerCourse, and basic public domain folk music in BoosterMusic. Anyway, I don't have anything yet, I was just investigating...

**Comment by fred-wang** [comment]
> @fred-wang you wrote _"... to contribute new music pieces"._ Do you some new music pieces that you would like to contribute??

I made an attempt at https://github.com/captnfab/PianoBooster/pull/267

**Comment by louis-barman** [comment]
Thanks so much for doing this, I will have a look at this on Tuesday.

**Comment by captnfab** [comment]
@louis-barman I switched the default branch to develop in 11/01, can you confirm that it did work?

**Comment by louis-barman** [comment]
@captnfab Yes thanks, I saw that immediately. The branch for this page https://github.com/captnfab/PianoBooster now always starts with the develop branch . New pull request now default to the develop branch. Thanks

**Comment by louis-barman** [comment]
Fixed in v1.0.0
